USE [Crypto]
GO
DBCC CHECKIDENT ('[Symbol]', RESEED, 0);
GO
INSERT INTO Symbol (SymbolName, DisplayName, DecimalPlaces, Active) VALUES
        ('BTC', 'Bitcoin (BTC)',	2,	1),
        ('ETH', 'Etherium (ETH)',	2,	1),
        ('BNB', 'Binance Coin (BNB)',	4,	1),
        ('ADA', 'Cardano (ADA)', 3, 1),
        ('DOT', 'Polkadot (DOT)', 2, 1),
        ('XRP', 'Ripple (XRP)', 4, 1),
        ('LTC', 'Litecoin (LTC)', 2, 1),
        ('LINK', 'Chainlink (LINK)', 2, 1),
        ('BCH', 'Bitcoin Cash (BCH)', 2, 1),
        ('XLM', 'Stellar (XLM)', 4, 1),
        ('UNI', 'Uniswap (UNI)', 2, 1),
        ('DOGE', 'Dogecoin (DOGE)', 4, 1),
        ('XEM', 'NEM (XEM)', 4, 0),
        ('ATOM', 'Cosmos (ATOM)', 2, 1),
        ('AAVE', 'AAVE (AAVE)', 2, 1),
        ('SOL', 'Solana (SOL)', 2, 1),
        ('XMR', 'Monero (XMR)', 2, 1),
        ('EOS', 'EOS (EOS)', 3, 1),
        ('TRX', 'Tron (TRX)', 5, 1),
        ('IOTA', 'MIOTA (IOTA)', 4, 1),
        ('THETA', 'Theta Network (THETA)', 3, 1),
        ('NEO', 'NEO (NEO)', 2, 1),
        ('XTZ', 'Tezos (XTZ)', 3, 1),
        ('VET', 'VeChain (VET)', 5, 1),
        ('DASH', 'DASH (DASH)', 2, 1),
        ('GRT', 'The Graph (GRT)', 4, 1),
        ('AVAX', 'Avalanche (AVAX)', 2, 1),
        ('KSM', 'Kasuma (KSM)', 2, 1),
        ('MKR', 'Maker (MKR)', 2, 1),
        ('EGLD', 'Elrond (EGLD)', 2, 1),
        ('FIL', 'FileCoin (FIL)', 2, 1),
        ('FTM', 'Fantom (FTM)', 4, 1),
        ('COMP', 'Compound (COMP)', 2, 1),
        ('CAKE', 'PancakeSwap (CAKE)', 2, 1),
        ('ZEC', 'ZCash (ZEC)', 2, 1),
        ('ETC', 'Etherium Classic (ETC)', 2, 1),
        ('RUNE', 'THORChain (RUNE)', 3, 1),
        ('NEAR', 'NEAR (NEAR)', 3, 1),
        ('WAVES', 'WAVES (WAVES)', 2, 0),
        ('STX', 'Stacks (STX)', 4, 1),
        ('HBAR', 'Hadera Hashgraph (HBAR)', 3, 1),
        ('MATIC', 'Polygon (MATIC)', 3, 1),
        ('ALGO', 'Algorand (ALGO)', 4, 1),
        ('BAT', 'Basic Attention Token (BAT)', 4, 1),
        ('LRC', 'Loopring (LRC)', 4, 1),
        ('QTUM', 'QTUM (QTUM)', 3, 1),
        ('HOT', 'Holo (HOT)', 6, 1),
        ('ENJ', 'Enjin Coin (ENJ)', 3, 1),
        ('CRV', 'Curve DAO Token (CRV)', 3, 1),
        ('SHIB', 'Shiba Inu (SHIB)', 8, 1),
        ('AXS', 'Axie Infinity (AXS)', 2, 1),
        ('ICP', 'Internet Computer (ICP)', 2, 1),
        ('SAND', 'The Sandbox (SAND)', 4, 1),
        ('MANA', 'Decentraland (MANA)', 4, 1),
        ('FLOW', 'FLOW (FLOW)', 2, 1),
        ('KLAY', 'Klaytn (KLAY)', 3, 1),
        ('ONE', 'Harmony (ONE)', 5, 1),
        ('AR', 'Arweave (AR)', 2, 1),
        ('AMP', 'AMP (AMP)', 5, 1),
        ('XEC', 'eCash (XEC)', 8, 1),
        ('QNT', 'Quant (QNT)', 2, 1),
        ('TFUEL', 'Theta Fuel (TFUEL)', 4, 1),
        ('CELO', 'CELO (CELO)', 3, 1),
        ('IOTX', 'IoTeX (IOTX)', 5, 1),
        ('DCR', 'Decred (DCR)', 2, 1),
        ('DGB', 'DigiByte (DBG)', 5, 1),
        ('ICX', 'ICON (ICX)', 3, 1),
        ('IOST', 'IOST (ISOT)', 5, 1),
        ('KNC', 'Kyber Network Crystal (KNC)', 3, 1),
        ('ONT', 'Ontology (ONT)', 4, 1),
        ('REN', 'REN (REN)', 4, 1),
        ('RVN', 'Ravencoin (RVN)', 5, 1),
        ('SC', 'Siacoin (SC)', 5, 1),
        ('SNX', 'Synthetix Network Token (SNX)', 3, 1),
        ('SUSHI', 'SUSHI (SUSHI)', 3, 1),
        ('SXP', 'SXP (SXP)', 3, 1),
        ('UMA', 'UMA (UMA)', 3, 1),
        ('YFI', 'yearn.finance (YFI)', 2, 1),
        ('ZEN', 'Horizen (ZEN)', 2, 1),
        ('ZIL', 'Zilliqa (ZIL)', 5, 1),
        ('ZRX', '0x (ZRX)', 4, 1),
        ('GNO', 'Gnosis (GNO)', 2, 1),
        ('LPT', 'Livepeer (LPT)', 2, 1),
        ('ANKR', 'ANKR (ANKR)', 5, 1),
        ('SYS', 'Syscoin (SYS)', 4, 1),
        ('SKL', 'SKALE (SKL)', 4, 1),
        ('PAXG', 'PAX Gold (PAXG)', 2, 1),
        ('FLUX', 'FLUX (FLUX)', 3, 1),
        ('DENT', 'DENT (DENT)', 6, 1),
        ('LSK', 'Lisk (LSK)', 3, 1),
        ('POWR', 'Power Ledger (POWR)', 4, 1),
        ('GALA', 'GALA (GALA)', 5, 1),
        ('FXS', 'Frax Share (FXS)', 3, 1),
        ('CVX', 'Convex Finance (CVX)', 2, 1),
        ('ROSE', 'Oasis Network (ROSE)', 5, 1),
        ('SCRT', 'Secret (SCRT)', 3, 1),
        ('SLP', 'Smooth Love Potion (SLP)', 4, 1),
        ('MINA', 'Mina Protocol (MINA)', 3, 1),
        ('1INCH', '1INCH (1INCH)', 3, 1),
        ('WAXP', 'WAX (WAXP)', 4, 1),
        ('CHZ', 'Chiliz (CHZ)', 4, 1),
        ('AUDIO', 'Audius (AUDIO)', 3, 1),
        ('KAVA', 'KAVA (KAVA)', 3, 1),
        ('IMX', 'Immutable X (IMX)', 3, 1),
        ('CKB', 'Nervos Network (CKB)', 5, 1),
        ('HIVE', 'HIVE (HIVE)', 4, 1),
        ('JST', 'JUST (JST)', 5, 1),
        ('ENS', 'Etherium Name Service (ENS)', 2, 1),
        ('C98', 'Coin98 (C98)', 3, 1),
        ('KDA', 'Kadena (KDA)', 3, 1),
        ('BSW', 'Biswap (BSW)', 4, 1),
        ('XNO', 'Nano (XNO)', 3, 1),
        ('INJ', 'Injective (INJ)', 3, 1),
        ('FET', 'Fetch.ai (FET)', 4, 1),
        ('APE', 'ApeCoin (APE)', 4, 1),
        ('OP', 'Optimism (OP)', 3, 1),
        ('APT', 'Aptos (APT)', 4, 1),
        ('ARB', 'Arbitrum (ARB)', 4, 1),
        ('SUI', 'Sui (SUI)', 4, 1),
        ('ASTR', 'Astar (ASTR)', 4, 1),
        ('OSMO', 'Osmosis (OSMO)', 4, 1),
        ('WOO', 'WOO (WOO)', 4, 1),
        ('NEXO', 'NEXO (NEXO)', 3, 1),
        ('ELF', 'aelf (ELF)', 4, 1),
        ('GAS', 'Gas (GAS)', 3, 1),
        ('AGIX', 'SingularityNET (AGIX)', 5, 1),
        ('MAGIC', 'Magic (MAGIC)', 4, 1),
        ('MASK', 'Mask Network (MASK)', 3, 1),
        ('API3', 'API3 (API3)', 3, 1),
        ('GLMR', 'Moonbeam (GLMR)', 4, 1),
        ('TRB', 'Tellor Tributes (TRB)', 2, 1),
		('LUNA', '(LUNA)', 2, 0),
		('FTT', '(FTT)', 2, 0),
		('BUSD', '(BUSD)', 4, 0),
		('BTT', '(BTT)', 7, 0),
		('PAX', '(PAX)', 4, 0),
		('NANO', '(NANO)', 2, 0),
		('OMG', '(OMG)', 4, 0),
		('BNT', '(BNT)', 2, 0),
		('NPXS', '(NPXS)', 7, 0),
		('HNT', '(HNT)', 2, 0),
		('TUSD', '(TUSD)', 4, 0),
		('BTG', '(BTG)', 2, 0),
		('POLY', '(POLY)', 4, 0),
		('SRM', '(SRM)', 3, 0),
		('TRIBE', '(TRIBE)', 4, 0),
		('USDP', '(USDP)', 4, 0),
		('ANY', '(ANY)', 2, 0),
		('OGN', '(OGN)', 4, 0)
GO

SELECT * FROM Symbol
SELECT ID, SymbolName, DisplayName, DecimalPlaces, Active, Rank, RankDate FROM Symbol, Ranking WHERE Symbol.ID = Ranking.SymbolID

SELECT
	S.*, R.*
FROM Symbol AS S
JOIN Ranking AS R ON (S.ID = R.SymbolID)
LEFT OUTER JOIN Ranking AS R2 ON (S.ID = R2.SymbolID AND (R.RankDate < R2.RankDate OR (R.RankDate = R2.RankDate AND R.SymbolID < R2.SymbolID)))
WHERE R2.SymbolID IS NULL AND S.Active = 1
ORDER BY R.Rank
